module.exports = function(app) {
  return {
    id: 'signalk-seamap-plugin',
    name: 'Global Seacharts based on OSM/Gebco/Emod',
    schema: () => { return {
      title: 'Seamap Charts',
      type: 'object',
      properties: {
        path: {
          type: 'string',
          title: 'Path to store offline pmtiles',
          description: `Enter path relative to ${app.config.configPath}. Defaults to /seamap/pmtiles`,
          default: `${app.config.configPath}/seamap/pmtiles`
        },
        stylesPath: {
          type: 'string',
          title: 'Path for MapLibreGL stylesheets.',
          description: `Enter path relative to ${app.config.configPath}. Defaults to /seamap/styles`,
          default: `${app.config.configPath}/seamap/styles`
        },
        tilesPath: {
          type: 'string',
          title: 'Path to cache ondemand generated tiles.',
          description: `Enter path relative to ${app.config.configPath}. Defaults to /seamap/tiles`,
          default: `${app.config.configPath}/seamap/tiles`
        },
        contourDepthLevels: {
          type: 'string',
          title: 'Bathymety contourlines',
          title: 'comma separated string with all depth levels for bathymetry contourlines',
          default: '2,5,10,20,50,100,250,500,1000,2000,3000,4000,5000'
        },
        bathymetryDepthLevels: {
          type: 'string',
          title: 'Bathymety depth polygons',
          description: 'comma separated string with all depth levels for bathymetry areas',
          default: '2,5,10,20,50'
        },

      }
    } },
    start: function() {
      this.started = true;
      app.registerResourceProvider({
        type: 'seamap',
        methods: {
          listResources: (type, query) => {
            return Promise.resolve({
              "bathymetry": {
                title: `bathymetry contourlines and areas generated from various DEM sources`,
                datasets: ['gebco', 'emod']
              },
              "dem": {
                title: `various terrainrgb datasets for bathymetry generation`,
                datasets: ['gebco', 'emod']
              },
              "seamap": { title: `osm seamarks vector-tiles` },
              "versatiles": { title: `osm land vector-tiles` },
              "mapterhorn": { title: `osm land DEM data in terrainrgb format` },
              "contour": { title: `land contourlines generated by mapterhorn data` },
            });
          },
          getResource: (type, id) => {
            return Promise.resolve({
              value: `seamap getResource(${type}, ${id})`
            });
          },
          setResource: (type, id, value) => {
            return Promise.reject(
              new Error(`Not implemented!\n Cannot set ${id} to ${value}`)
            )
          },
          deleteResource: (type, id) => {
            return Promise.reject(
              new Error(`Not implemented!\n Cannot delete ${id}`)
            )
          }
        }
      })
    },
    stop: function() {
      this.started = false;
    },
    registerWithRouter: (router) => {
      router.get('/listPmtilesTiles', (req, res) => res.json({message: 'test ok'}));
      router.get('/downloadPmtilesTile', (req, res) => res.json({message: 'test ok'}));
      router.get('/isPmtilesCmdInstalled', (req, res) => res.json({message: 'test ok'}));
    },
    getOpenApi: () => require('./openApi'),
    app: app
  }
}